rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  irc: "irc.freenode.org#celluloid"
